#include "control_mode_position.h"
#include "control_ball_common.h"
#include "system_state.h"
#include <stdio.h>

/*
 * Position mode receives the desired Roll/Pitch generated by the Jetson
 * controller and applies them directly to the ball-control layer.
 *
 * The STM32 does not calculate the position-control PID. The desired
 * ball position is handled on the Jetson side and converted to the
 * Roll/Pitch setpoints received through CAN.
 */
void control_mode_position_enter(void)
{
    /*
     * Preserve the current setpoint when entering Position mode.
     * The desired ball position is controlled by the UI and must remain
     * unchanged across mode transitions.
     *
     * Camera supervision in control_mode_position_step() provides the
     * required failsafe if the Jetson connection is lost.
     */
}

void control_mode_position_step(float dt)
{
    /*
     * Position mode does not run a local PID controller.
     * Keep dt in the common mode interface so all control modes share
     * the same state-machine callback signature.
     */
    (void)dt;

    bool camera_ok = camera_state_is_ok();

    if (camera_ok) {
        /*
         * Apply the latest Roll/Pitch setpoints received from the Jetson.
         * The MCU only executes the requested attitude command; position
         * control remains on the Jetson.
         */
        setpoint_t sp;

        if (setpoint_get(&sp)) {
            control_ball_apply_rp(sp.Roll_d, sp.Pitch_d);
        }

        /*
         * If the setpoint cannot be read, keep the previous actuator command.
         * This avoids applying an incomplete or inconsistent control update.
         */
    } else {
        /*
         * Return directly to neutral when the Jetson/camera path is not
         * healthy. Do not reuse the last received setpoint because it may
         * no longer represent a valid control command.
         */
        control_ball_apply_rp(0.0f, 0.0f);
    }
}
