#include "control_mode_balance.h"
#include "control_ball_common.h"
#include "trajectory.h"
#include "servo_actuator.h"
#include "system_state.h"

#include <stdbool.h>
#include <math.h>
#include "main.h"
#include <stdio.h>

/*
 * The trajectory engine operates in Roll/Pitch/Height space before IK.
 *
 * Jetson setpoints may arrive continuously at a high rate. Each significant
 * target change therefore replans from the current trajectory state rather
 * than starting a new trajectory from zero velocity.
 *
 * The actuator layer provides an additional servo-space slew-rate limit after
 * IK. These two layers protect different spaces and are intentionally kept
 * independent.
 */

/*
 * The servo datasheet provides the theoretical maximum angular velocity.
 * This value is used by the trajectory layer as an upper bound; the actuator
 * layer still provides the final calibrated servo-space limit.
 */
#define SERVO_V_MAX_THEORETICAL_DEG_S   (60.0f / 0.085f)

/*
 * The second-order IK model has no constant deg-to-us conversion because
 * its local gain varies with the operating point.
 *
 * Use the servo angular speed as the Roll/Pitch trajectory limit and derive
 * the acceleration limit from the selected acceleration horizon.
 */
#define TRAJ_ROLL_PITCH_V_MAX   (SERVO_V_MAX_THEORETICAL_DEG_S)
#define TRAJ_ROLL_PITCH_A_MAX   (TRAJ_ROLL_PITCH_V_MAX / 0.015f)

/*
 * Height conversion must match the conversion used by control_ball_common.c.
 *
 * Both values represent the same experimentally measured servo response.
 * Keeping the conversion identical prevents the trajectory and IK layers
 * from applying different height scales.
 */
#define HEIGHT_K_US_PER_MM      (290.0f / 13.0f)

/*
 * Derive height velocity and acceleration limits directly from the actuator
 * limits so trajectory constraints remain synchronized with servo tuning.
 */
#define TRAJ_HEIGHT_V_MAX \
    (SERVO_SLEW_MAX_US_PER_S / HEIGHT_K_US_PER_MM)

#define TRAJ_HEIGHT_A_MAX \
    (SERVO_ACCEL_MAX_US_PER_S2 / HEIGHT_K_US_PER_MM)

/*
 * Ignore target changes smaller than the measurement and communication noise
 * floor. This prevents unnecessary replanning when Jetson setpoints fluctuate
 * around an already active target.
 */
#define TARGET_EPSILON_DEG   0.05f
#define TARGET_EPSILON_MM    0.05f

/*
 * Reject an update interval that is too large to represent a normal control
 * cycle. Updating the trajectory with such a value could advance the command
 * by an unintended amount after a task scheduling delay.
 */
#define DT_MAX   0.5f

/* Ball enable state is owned by this control mode. */
static bool s_ball_on = false;

/*
 * Current trajectory command state.
 *
 * These values represent the commanded Roll/Pitch/Height state generated by
 * the trajectory engine. They are used as the initial position when a new
 * trajectory is replanned.
 */
static trajectory_state_t s_traj_roll;
static trajectory_state_t s_traj_pitch;
static trajectory_state_t s_traj_height;

static float s_roll_cur   = 0.0f;
static float s_pitch_cur  = 0.0f;
static float s_height_cur = 0.0f;

/*
 * Last accepted targets from Jetson.
 *
 * Epsilon comparison against these values prevents unnecessary trajectory
 * replanning caused by small setpoint variations.
 */
static float s_roll_target   = 0.0f;
static float s_pitch_target  = 0.0f;
static float s_height_target = 0.0f;

/*
 * False until the first valid trajectory is created after entering the mode.
 * This guarantees the first target is always processed even when it is zero.
 */
static bool s_traj_inited = false;

void control_mode_balance_set_ball_on(bool on)
{
    s_ball_on = on;
}

bool control_mode_balance_get_ball_on(void)
{
    return s_ball_on;
}

void control_mode_balance_enter(void)
{
    /*
     * Enter Balance mode with Ball disabled.
     *
     * The operator must explicitly enable balancing after entering the mode,
     * preventing stale setpoints from a previous session from being applied
     * immediately.
     */
    s_ball_on = false;

    /*
     * Clear all trajectory state so the new session cannot inherit position,
     * velocity, or acceleration from a previous mode entry.
     */
    s_traj_roll   = (trajectory_state_t){0};
    s_traj_pitch  = (trajectory_state_t){0};
    s_traj_height = (trajectory_state_t){0};

    s_roll_cur = 0.0f;
    s_pitch_cur = 0.0f;
    s_height_cur = 0.0f;

    s_roll_target = 0.0f;
    s_pitch_target = 0.0f;
    s_height_target = 0.0f;

    s_traj_inited = false;
}

void control_mode_balance_step(float dt)
{
    /*
     * Ignore invalid timing information rather than advancing the trajectory
     * with a value that does not represent the actual control-loop interval.
     */
    if (dt <= 0.0f || dt > DT_MAX)
    {
        return;
    }

    static bool last_ball_on = false;

    bool camera_ok = camera_state_is_ok();

    if (s_ball_on != last_ball_on)
    {
        printf(
            "Ball:ON = %d (camera_ok=%d)\r\n",
            s_ball_on,
            camera_ok
        );

        last_ball_on = s_ball_on;
    }

    if (s_ball_on && camera_ok)
    {
        /*
         * Ball ON:
         * Receive the latest Jetson target, replan when it changes
         * significantly, then advance all three trajectories.
         */
        setpoint_t sp;

        if (setpoint_get(&sp))
        {
            /*
             * Replan from the current trajectory state so a new Jetson target
             * does not introduce a discontinuity in velocity or acceleration.
             */
            if (!s_traj_inited ||
                fabsf(sp.Roll_d - s_roll_target) >= TARGET_EPSILON_DEG ||
                fabsf(sp.Pitch_d - s_pitch_target) >= TARGET_EPSILON_DEG ||
                fabsf(sp.Height_d - s_height_target) >= TARGET_EPSILON_MM)
            {
                trajectory_replan(
                    &s_traj_roll,
                    s_roll_cur,
                    s_traj_roll.v,
                    s_traj_roll.a,
                    sp.Roll_d,
                    TRAJ_ROLL_PITCH_V_MAX,
                    TRAJ_ROLL_PITCH_A_MAX
                );

                trajectory_replan(
                    &s_traj_pitch,
                    s_pitch_cur,
                    s_traj_pitch.v,
                    s_traj_pitch.a,
                    sp.Pitch_d,
                    TRAJ_ROLL_PITCH_V_MAX,
                    TRAJ_ROLL_PITCH_A_MAX
                );

                trajectory_replan(
                    &s_traj_height,
                    s_height_cur,
                    s_traj_height.v,
                    s_traj_height.a,
                    sp.Height_d,
                    TRAJ_HEIGHT_V_MAX,
                    TRAJ_HEIGHT_A_MAX
                );

                s_roll_target = sp.Roll_d;
                s_pitch_target = sp.Pitch_d;
                s_height_target = sp.Height_d;

                s_traj_inited = true;
            }
        }

        /*
         * A failed setpoint read does not interrupt the active trajectory.
         * The last valid target continues to execute until a new target is
         * available or the camera failsafe becomes active.
         */
        trajectory_update(
            &s_traj_roll,
            dt,
            &s_roll_cur,
            NULL,
            NULL
        );

        trajectory_update(
            &s_traj_pitch,
            dt,
            &s_pitch_cur,
            NULL,
            NULL
        );

        trajectory_update(
            &s_traj_height,
            dt,
            &s_height_cur,
            NULL,
            NULL
        );

        control_ball_apply_rph(
            s_roll_cur,
            s_pitch_cur,
            s_height_cur
        );
    }
    else
    {
        /*
         * Ball OFF or camera failsafe:
         * Replan the active trajectory toward the level-platform target.
         *
         * The same trajectory limits are used here because this is a controlled
         * return to neutral, not an emergency-stop path.
         */
        if (!s_traj_inited ||
            fabsf(s_roll_target) >= TARGET_EPSILON_DEG ||
            fabsf(s_pitch_target) >= TARGET_EPSILON_DEG ||
            fabsf(s_height_target) >= TARGET_EPSILON_MM)
        {
            trajectory_replan(
                &s_traj_roll,
                s_roll_cur,
                s_traj_roll.v,
                s_traj_roll.a,
                0.0f,
                TRAJ_ROLL_PITCH_V_MAX,
                TRAJ_ROLL_PITCH_A_MAX
            );

            trajectory_replan(
                &s_traj_pitch,
                s_pitch_cur,
                s_traj_pitch.v,
                s_traj_pitch.a,
                0.0f,
                TRAJ_ROLL_PITCH_V_MAX,
                TRAJ_ROLL_PITCH_A_MAX
            );

            trajectory_replan(
                &s_traj_height,
                s_height_cur,
                s_traj_height.v,
                s_traj_height.a,
                0.0f,
                TRAJ_HEIGHT_V_MAX,
                TRAJ_HEIGHT_A_MAX
            );

            s_roll_target = 0.0f;
            s_pitch_target = 0.0f;
            s_height_target = 0.0f;

            s_traj_inited = true;
        }

        trajectory_update(
            &s_traj_roll,
            dt,
            &s_roll_cur,
            NULL,
            NULL
        );

        trajectory_update(
            &s_traj_pitch,
            dt,
            &s_pitch_cur,
            NULL,
            NULL
        );

        trajectory_update(
            &s_traj_height,
            dt,
            &s_height_cur,
            NULL,
            NULL
        );

        control_ball_apply_rph(
            s_roll_cur,
            s_pitch_cur,
            s_height_cur
        );
    }
}
