#ifndef CONTROL_MODE_POSITION_H
#define CONTROL_MODE_POSITION_H

/**
 * @file    control_mode_position.h
 * @brief   Position control mode interface.
 *
 * Position mode applies Roll/Pitch setpoints generated by the Jetson
 * position controller. The STM32 does not calculate the position-control
 * PID; it only applies the received attitude command to the ball-control
 * layer.
 *
 * When the Jetson/camera path is unavailable, the mode automatically
 * commands neutral attitude as a failsafe.
 */

void control_mode_position_enter(void);

/**
 * @brief Execute one Position control cycle.
 *
 * Applies the latest Roll/Pitch setpoints received from the Jetson while
 * the camera path is healthy. If the camera state is invalid, the control
 * output is returned to neutral.
 *
 * @param dt Control-loop period in seconds.
 */
void control_mode_position_step(float dt);

#endif /* CONTROL_MODE_POSITION_H */
