#ifndef SYSTEM_STATE_HPP
#define SYSTEM_STATE_HPP

#include <cstdint>
#include "seqlock.hpp"

/*
 * STM32 attitude telemetry received through CAN.
 *
 * roll/pitch are expressed in degrees.
 * vroll/vpitch are angular rates.
 * height is expressed in millimeters.
 */
struct telemetry_attitude_t
{
    seqlock_t lock;

    float roll = 0;
    float pitch = 0;

    float vroll = 0;
    float vpitch = 0;

    float height = 0;
};

void telemetry_attitude_write(
    telemetry_attitude_t& s,
    float roll,
    float pitch,
    float vroll,
    float vpitch,
    float height
);

void telemetry_attitude_read(
    const telemetry_attitude_t& s,
    float& roll,
    float& pitch,
    float& vroll,
    float& vpitch,
    float& height
);

/*
 * Servo position telemetry received from STM32.
 *
 * Values correspond to the three platform actuators transmitted in
 * CAN message 0x102.
 */
struct telemetry_servo_t
{
    seqlock_t lock;

    int32_t S1 = 0;
    int32_t S2 = 0;
    int32_t S3 = 0;
};

void telemetry_servo_write(
    telemetry_servo_t& s,
    int32_t s1,
    int32_t s2,
    int32_t s3
);

void telemetry_servo_read(
    const telemetry_servo_t& s,
    int32_t& s1,
    int32_t& s2,
    int32_t& s3
);

/*
 * STM32 robot state received through CAN message 0x103.
 *
 * mode contains the current operating mode.
 * bits contains the associated robot status flags.
 */
struct telemetry_robot_state_t
{
    seqlock_t lock;

    uint8_t mode = 0;
    uint8_t bits = 0;
};

void telemetry_robot_state_write(
    telemetry_robot_state_t& s,
    uint8_t mode,
    uint8_t bits
);

void telemetry_robot_state_read(
    const telemetry_robot_state_t& s,
    uint8_t& mode,
    uint8_t& bits
);

/*
 * Ball state generated by the Jetson vision pipeline.
 *
 * Position and velocity are transmitted through CAN messages 0x200,
 * 0x201, and 0x202.
 *
 * Position and velocity values are represented in the protocol units
 * defined by the CAN interface.
 */
struct ball_state_t
{
    seqlock_t lock;

    int16_t Ballx = 0;
    int16_t Bally = 0;

    int16_t vBallx = 0;
    int16_t vBally = 0;

    uint8_t ball_detected = 0;
};

void ball_state_write_pos(
    ball_state_t& s,
    int16_t x,
    int16_t y
);

void ball_state_write_vel(
    ball_state_t& s,
    int16_t vx,
    int16_t vy
);

void ball_state_write_detected(
    ball_state_t& s,
    uint8_t detected
);

void ball_state_read(
    const ball_state_t& s,
    int16_t& x,
    int16_t& y,
    int16_t& vx,
    int16_t& vy,
    uint8_t& detected
);

/*
 * Ball position requested by STM32.
 *
 * The values are received through CAN message 0x104 and represent the
 * position that the STM32 control system expects the ball to reach.
 *
 * The CAN RX task is the single writer for this state.
 */
struct ball_desired_t
{
    seqlock_t lock;

    int16_t Ballx_d = 0;
    int16_t Bally_d = 0;

    int16_t Ballheight_d = 0;
};

void ball_desired_write(
    ball_desired_t& s,
    int16_t x_d,
    int16_t y_d,
    int16_t height_d
);

void ball_desired_read(
    const ball_desired_t& s,
    int16_t& x_d,
    int16_t& y_d,
    int16_t& height_d
);

/*
 * Desired platform attitude generated by the Jetson control loop.
 *
 * roll_d and pitch_d are expressed in degrees.
 * height_d is expressed in millimeters.
 *
 * TaskCanTx is responsible for converting these values into the CAN
 * protocol representation.
 */
struct attitude_desired_t
{
    seqlock_t lock;

    float roll_d = 0.f;
    float pitch_d = 0.f;
    float height_d = 0.f;
};

void attitude_desired_write(
    attitude_desired_t& s,
    float roll_d,
    float pitch_d,
    float height_d
);

void attitude_desired_read(
    const attitude_desired_t& s,
    float& roll_d,
    float& pitch_d,
    float& height_d
);

/*
 * Records STM32 communication activity and reports whether the connection
 * is still considered healthy.
 */
void stm32_heartbeat_mark();

bool stm32_state_is_ok();

/*
 * Shared Jetson runtime state.
 *
 * Each subsystem owns the fields it produces while other tasks access the
 * data through the corresponding seqlock-protected read/write functions.
 */
struct SystemState
{
    telemetry_attitude_t attitude;
    telemetry_servo_t servo;
    telemetry_robot_state_t robot_state;

    ball_state_t ball;
    ball_desired_t ball_desired;

    attitude_desired_t attitude_desired;
};

/*
 * Returns the process-wide shared system state.
 */
SystemState& system_state();

#endif