#ifndef TASK_CONTROL_LOOP_HPP
#define TASK_CONTROL_LOOP_HPP

#include <thread>
#include <atomic>
#include <memory>
#include <cstdint>

#include "pid_controller.hpp"
#include "trajectory.hpp"

/*
 * Runs the J7 control loop.
 *
 * The loop consumes the latest ball state produced by TaskBallDetect,
 * computes independent X/Y PID outputs, and publishes the desired attitude
 * for TaskCanTx.
 *
 * The loop runs at 100 Hz to match the CAN transmit rate and keep the
 * control output current when TaskCanTx reads it.
 *
 * Safety behavior:
 * - No detected ball: reset both PID controllers and command zero attitude.
 * - STM32 state not healthy: reset both PID controllers and command zero
 *   attitude.
 *
 * Setpoint selection depends on the current robot mode:
 * - BALANCE: generated by BalanceTrajectoryController.
 * - POSITION: read from system_state().ball_desired.
 * - HOME/CALIB/MANUAL: fixed zero setpoint.
 */
class TaskControlLoop
{
public:
    TaskControlLoop() = default;
    ~TaskControlLoop();

    TaskControlLoop(const TaskControlLoop&) = delete;
    TaskControlLoop& operator=(const TaskControlLoop&) = delete;

    /*
     * Conservative default gains and output limit for initial hardware tests.
     * The control authority can be increased progressively after the basic
     * control loop has been verified.
     */
    bool start(
        float kp = 0.1f,
        float ki = 0.0f,
        float kd = 0.015f,
        float out_limit_deg = 3.0f
    );

    void stop();

    bool is_running() const
    {
        return running_.load(
            std::memory_order_relaxed
        );
    }

private:
    void run();

    std::unique_ptr<PIDController> pid_x_;
    std::unique_ptr<PIDController> pid_y_;

    std::unique_ptr<std::thread> thread_;

    std::atomic<bool> running_{ false };

    /*
     * Generates the automatic setpoint trajectory used by BALANCE mode.
     */
    BalanceTrajectoryController balance_traj_;

    /*
     * Stores the previous operating mode so that entering BALANCE can be
     * detected and the trajectory can be reset exactly once.
     *
     * 0xFF is outside the valid opmode range and guarantees that the first
     * BALANCE cycle is treated as a mode transition.
     */
    uint8_t last_mode_ = 0xFF;

    /*
     * Accumulates continuous ball/STM32 loss time.
     *
     * PID output is forced to zero immediately when the ball or STM32 state
     * becomes invalid. The trajectory is reset only after the loss persists
     * beyond the configured threshold, allowing brief camera dropouts.
     */
    float ball_loss_elapsed_s_ = 0.f;

    static constexpr float kBallLossResetThresholdS = 0.3f;
};

#endif