/**
 * @file    task_state_machine.c
 * @brief   System state-machine task.
 *
 * Owns the top-level system state and performs all state transitions in
 * response to events received through StateRequestQueueHandle.
 *
 * Only this task publishes system-state transitions. Other tasks request
 * transitions by sending state events through the shared queue.
 */

#include "task_state_machine.h"

#include "system_state.h"

#include "cmsis_os2.h"
#include "main.h"

extern osMessageQueueId_t StateRequestQueueHandle;

void StartStateMachine(void *argument)
{
    (void)argument;

    state_event_t evt;

    /*
     * The system starts in INIT so the state machine can evaluate the
     * self-test and calibration results before allowing normal operation.
     */
    system_state_publish(STATE_INIT);

    /*
     * The current startup sequence requires calibration to be completed
     * before the system becomes operational.
     *
     * These states are published during startup until the corresponding
     * self-test and calibration tasks are responsible for generating the
     * runtime transition events.
     */
    system_state_publish(STATE_CALIBRATION);
    system_state_publish(STATE_READY);

    for (;;)
    {
        /*
         * State transitions are serialized through the event queue.
         *
         * Blocking here is intentional: the state machine has no periodic
         * processing requirement and should react only to explicit events.
         */
        if (osMessageQueueGet(
                StateRequestQueueHandle,
                &evt,
                NULL,
                osWaitForever
            ) == osOK)
        {
            system_state_t cur =
                system_state_get();

            /*
             * A fault event is an immediate safety transition.
             *
             * Do not wait for another event to process STATE_ERROR because
             * the state-machine queue may remain blocked indefinitely when
             * the fault is the final event generated by the system.
             */
            if (evt == EVT_FAULT_DETECTED)
            {
                system_state_publish(STATE_ERROR);
                system_state_publish(STATE_SAFE_MODE);

                continue;
            }

            switch (cur)
            {
                case STATE_INIT:

                    if (evt == EVT_SELFTEST_FAIL)
                    {
                        system_state_publish(STATE_ERROR);
                    }
                    else if (evt == EVT_CALIB_DONE)
                    {
                        system_state_publish(STATE_READY);
                    }
                    else if (evt == EVT_SELFTEST_OK)
                    {
                        system_state_publish(STATE_CALIBRATION);
                    }

                    break;

                case STATE_CALIBRATION:

                    if (evt == EVT_CALIB_DONE)
                    {
                        system_state_publish(STATE_READY);
                    }
                    else if (evt == EVT_CALIB_FAIL)
                    {
                        system_state_publish(STATE_ERROR);
                    }

                    break;

                case STATE_READY:

                    if (evt == EVT_BTN_RUN)
                    {
                        system_state_publish(STATE_RUN);
                    }
                    else if (evt == EVT_BTN_SLEEP)
                    {
                        system_state_publish(STATE_SLEEP);
                    }

                    break;

                case STATE_RUN:

                    if (evt == EVT_BTN_STOP)
                    {
                        system_state_publish(STATE_READY);
                    }
                    /*
                     * Control modes do not modify the global system state
                     * directly. They report completion through events so
                     * state ownership remains centralized in this task.
                     */
                    else if (evt == EVT_HOME_DONE)
                    {
                        system_state_publish(STATE_READY);
                    }
                    else if (evt == EVT_MODE_CALIB_DONE)
                    {
                        system_state_publish(STATE_READY);
                    }
                    else if (evt == EVT_MODE_CALIB_FAILED)
                    {
                        system_state_publish(STATE_ERROR);
                    }

                    break;

                case STATE_SLEEP:

                    if (evt == EVT_BTN_WAKE)
                    {
                        system_state_publish(STATE_INIT);
                    }

                    break;

                case STATE_ERROR:

                    /*
                     * STATE_ERROR is a protected intermediate state.
                     * Any subsequent event advances the system into
                     * SAFE_MODE unless the state is handled explicitly
                     * before entering this case.
                     */
                    system_state_publish(STATE_SAFE_MODE);

                    break;

                case STATE_SAFE_MODE:

                    /*
                     * Recovery from SAFE_MODE requires an explicit manual
                     * acknowledgement before restarting initialization.
                     */
                    if (evt == EVT_MANUAL_RESET_ACK)
                    {
                        system_state_publish(STATE_INIT);
                    }

                    break;

                default:

                    /*
                     * Ignore events received while the state value is
                     * outside the defined state-machine range.
                     */
                    break;
            }
        }
    }
}
