#ifndef BSP_BUTTONS_H
#define BSP_BUTTONS_H

#include <stdint.h>
#include "cmsis_os2.h"

/*
 * Button input abstraction.
 *
 * This module separates GPIO/EXTI handling from application-level
 * button actions. The BSP is responsible only for:
 *
 *     GPIO EXTI -> debounce -> button event
 *
 * Button IDs are mapped directly to the hardware definitions in main.h:
 *
 *     BTN1 -> GPIOF1
 *     BTN2 -> GPIOE2
 *     BTN3 -> GPIOE3
 *     BTN4 -> GPIOE4
 *     BTN5 -> GPIOE5
 *     BTN6 -> GPIOE6
 *
 * BTN1 supports both short-press and long-press detection and therefore
 * uses both rising and falling EXTI edges.
 *
 * BTN2..BTN6 use falling-edge EXTI and generate a short-press event
 * after debounce confirmation.
 *
 * Application-specific actions such as LEFT, RIGHT, UP, DOWN, or EXIT
 * are intentionally handled outside this BSP module.
 */
typedef enum
{
    BTN_ID_1 = 0,   /* GPIOF1: short-press or long-press input */
    BTN_ID_2,       /* GPIOE2 */
    BTN_ID_3,       /* GPIOE3 */
    BTN_ID_4,       /* GPIOE4 */
    BTN_ID_5,       /* GPIOE5 */
    BTN_ID_6,       /* GPIOE6 */
    BTN_ID_COUNT
} button_id_t;

/*
 * Button event types generated by the BSP.
 *
 * BTN_EVT_SHORT_PRESS:
 *   - BTN2..BTN6: generated after a valid falling-edge debounce.
 *   - BTN1: generated when the button is released before the
 *           long-press threshold.
 *
 * BTN_EVT_LONG_PRESS:
 *   - Generated only for BTN1.
 *   - Generated as soon as the long-press threshold is reached;
 *     release of the button is not required.
 */
typedef enum
{
    BTN_EVT_SHORT_PRESS = 0,
    BTN_EVT_LONG_PRESS
} button_event_type_t;

/*
 * Debounced button event delivered to the application layer.
 */
typedef struct
{
    button_id_t         id;
    button_event_type_t type;
} button_event_t;

/*
 * Long-press threshold for BTN1.
 */
#define BTN_LONGPRESS_MS   600u

/*
 * Button debounce interval.
 *
 * A new EXTI edge resets the one-shot debounce timer. An event is
 * generated only after the input remains stable for this interval.
 */
#define BTN_DEBOUNCE_MS    25u

/*
 * Capacity of the application-owned button event queue.
 *
 * The queue is created by CubeMX/FreeRTOS initialization in main.c.
 * This value documents the expected queue depth and must remain
 * consistent with the corresponding RTOS configuration.
 */
#define BTN_EVENT_QUEUE_LEN  16u

/*
 * Application-owned button event queue.
 *
 * ButtonEventQueueHandle is created by MX_FREERTOS_Init() in main.c.
 * This BSP only publishes events to the existing queue and must not
 * create or redefine it.
 *
 * Timer callbacks execute in the FreeRTOS Timer Service Task context,
 * so CMSIS-RTOS2 queue APIs can be used directly.
 */
extern osMessageQueueId_t ButtonEventQueueHandle;

/*
 * @brief Initialize button debounce and long-press timers.
 *
 * Must be called after the RTOS objects have been created, including
 * ButtonEventQueueHandle.
 */
void buttons_init(void);

/*
 * @brief Process a button EXTI event.
 *
 * This function is called from HAL_GPIO_EXTI_Callback() and therefore
 * executes in interrupt context.
 *
 * Only ISR-safe FreeRTOS APIs may be used from this function.
 * The actual button event generation is deferred to the timer
 * callback running in the FreeRTOS Timer Service Task.
 *
 * @param GPIO_Pin GPIO pin associated with the EXTI event.
 */
void buttons_exti_handler(uint16_t GPIO_Pin);

#endif /* BSP_BUTTONS_H */
