/**
 * @file    task_can_tx.cpp
 * @brief   Periodic CAN transmission task.
 *
 * Publishes Jetson vision and control state to STM32 at a fixed rate.
 *
 * The task is responsible for encoding ball measurements, desired platform
 * attitude, and the Jetson heartbeat according to the shared CAN protocol.
 */

#include "task_can_tx.hpp"
#include "task_watchdog.hpp"
#include "system_state.hpp"
#include "can_protocol.h"

#include <cstdio>
#include <chrono>
#include <cmath>
#include <pthread.h>

bool TaskCanTx::start(const std::string& ifname)
{
    if (running_.load())
    {
        return true;
    }

    if (!can_.open(ifname))
    {
        std::printf(
            "TaskCanTx: khong mo duoc %s\n",
            ifname.c_str()
        );

        return false;
    }

    running_.store(true);

    thread_ =
        std::make_unique<std::thread>(
            &TaskCanTx::run,
            this
            );

    return true;
}

void TaskCanTx::stop()
{
    if (!running_.load())
    {
        return;
    }

    running_.store(false);

    if (
        thread_ &&
        thread_->joinable())
    {
        thread_->join();
    }

    can_.close();
}

TaskCanTx::~TaskCanTx()
{
    stop();
}

void TaskCanTx::run()
{
    std::printf(
        "TaskCanTx: STARTED\n"
    );

    /*
     * CAN transmission carries the control command generated by
     * TaskControlLoop.
     *
     * Keep this task below the control-loop priority while still giving it
     * real-time scheduling so command transmission is not starved by
     * CPU-intensive vision processing.
     */
    struct sched_param sp;

    sp.sched_priority = 70;

    if (
        pthread_setschedparam(
            pthread_self(),
            SCHED_FIFO,
            &sp) != 0)
    {
        std::fprintf(
            stderr,
            "TaskCanTx: khong set duoc SCHED_FIFO "
            "(can CAP_SYS_NICE/sudo), chay priority mac dinh - "
            "co the bi doi CPU boi TaskControlLoop/TaskBallDetect\n"
        );
    }

    using clock =
        std::chrono::steady_clock;

    auto next_wake =
        clock::now();

    /*
     * Transmit the control/telemetry set at 100 Hz so STM32 receives fresh
     * ball measurements and desired attitude commands with a deterministic
     * update period.
     */
    const auto period =
        std::chrono::milliseconds(10);

    uint8_t heartbeat_counter = 0;

    while (running_.load())
    {
        next_wake += period;

        uint8_t buf[8];

        /*
         * Read the latest ball measurement produced by TaskBallDetect.
         *
         * Position and velocity use the compact signed 16-bit protocol
         * representation, while detection state is transmitted separately.
         */
        int16_t x;
        int16_t y;
        int16_t vx;
        int16_t vy;
        uint8_t detected;

        ball_state_read(
            system_state().ball,
            x,
            y,
            vx,
            vy,
            detected
        );

        can_wr_i16le(
            &buf[0],
            x
        );

        can_wr_i16le(
            &buf[2],
            y
        );

        can_.send(
            CAN_ID_BALL_POS,
            4,
            buf
        );

        can_wr_i16le(
            &buf[0],
            vx
        );

        can_wr_i16le(
            &buf[2],
            vy
        );

        can_.send(
            CAN_ID_BALL_VEL,
            4,
            buf
        );

        buf[0] =
            detected;

        can_.send(
            CAN_ID_BALL_STATE,
            1,
            buf
        );

        /*
         * Read the complete desired attitude generated by the control loop.
         *
         * Roll and pitch are encoded with a 0.01-degree resolution.
         * Height is encoded directly in millimeters.
         */
        float roll_d;
        float pitch_d;
        float height_d;

        attitude_desired_read(
            system_state().attitude_desired,
            roll_d,
            pitch_d,
            height_d
        );

        int16_t roll_d_raw =
            (int16_t)(
                roll_d * 100.0f
                );

        int16_t pitch_d_raw =
            (int16_t)(
                pitch_d * 100.0f
                );

        /*
         * Height uses millimeters directly rather than the 0.01 scaling
         * applied to roll and pitch.
         *
         * This matches the STM32 CAN decoder for bytes 4..5.
         */
        int16_t height_d_raw =
            (int16_t)std::lround(
                height_d
            );

        can_wr_i16le(
            &buf[0],
            roll_d_raw
        );

        can_wr_i16le(
            &buf[2],
            pitch_d_raw
        );

        can_wr_i16le(
            &buf[4],
            height_d_raw
        );

        /*
         * Send all three desired attitude components in one frame so STM32
         * receives a consistent control command set.
         */
        can_.send(
            CAN_ID_ATTITUDE_DESIRED,
            6,
            buf
        );

        /*
         * Increment the heartbeat counter for diagnostics and transmit it
         * independently from the control payload.
         */
        buf[0] =
            heartbeat_counter++;

        can_.send(
            CAN_ID_HEARTBEAT_RX,
            1,
            buf
        );

        std::this_thread::sleep_until(
            next_wake
        );

        /*
         * Report successful completion of one periodic TX cycle.
         */
        task_alive_mark(
            ALIVE_BIT_CAN_TX
        );
    }

    std::printf(
        "TaskCanTx: STOPPED\n"
    );
}